In [7]:
import numpy as np
from sklearn.metrics import f1_score, precision_score,  recall_score

In [43]:
no_samples = 10
lengths = np.random.choice(range(5, 20), no_samples)

y_true = []
y_pred = []

for i in range(no_samples):
    l = lengths[i]
    
    ss = (np.random.uniform(0, 1, (2, l))  > 0.3).astype(int)
    print(l, ss)
    yt, yp = ss[0, :], ss[1, :]
    y_true.append(yt.tolist())
    y_pred.append(yp.tolist())

9 [[1 1 0 0 1 1 0 1 1]
 [1 1 1 0 1 1 1 1 1]]
17 [[1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0]
 [1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1]]
19 [[0 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0]
 [1 1 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 0]]
5 [[1 1 1 1 1]
 [1 1 1 1 1]]
8 [[1 1 1 0 0 0 0 1]
 [0 0 1 0 1 1 1 1]]
19 [[1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1]
 [1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1]]
7 [[1 1 0 0 0 0 1]
 [1 1 1 0 1 0 0]]
12 [[1 1 1 0 1 1 1 1 0 1 1 1]
 [0 1 0 1 1 1 1 0 1 1 1 1]]
10 [[1 1 1 1 1 1 0 0 1 1]
 [1 1 1 0 1 1 1 1 1 1]]
12 [[1 1 0 1 0 0 1 1 0 1 1 0]
 [1 1 1 1 0 1 0 1 1 1 0 1]]


In [49]:
np.sum(lengths)

118

In [47]:
import itertools

merged = list(itertools.chain(*y_true))

In [48]:
len(merged)

118

In [42]:
y_true[0]

[1, 0, 0, 1, 1]

In [53]:
f1s = []
p1s = []
r1s = []

for i in range(len(y_true)):
    pair = (y_true[i], y_pred[i])
    
    f = f1_score(*pair)
    f1s.append(f)
    
    p = precision_score(*pair)
    p1s.append(p)
    
    r = recall_score(*pair)
    r1s.append(r)
    print('Sample %d: f1=%.4f, precision=%.4f, recall=%.4f' % (i, f, p, r))
print("avg f1=%.4f, precision=%.4f, recall=%.4f" % (np.mean(f1s), np.mean(p1s), np.mean(r1s)))

fy_true = list(itertools.chain(*y_true))
fy_pred = list(itertools.chain(*y_pred))
print('flatten f1=%.4f, precision=%.4f, recall=%.4f' %
      (f1_score(fy_true, fy_pred), precision_score(fy_true, fy_pred), recall_score(fy_true, fy_pred)))

Sample 0: f1=0.8571, precision=0.7500, recall=1.0000
Sample 1: f1=0.8148, precision=0.7857, recall=0.8462
Sample 2: f1=0.6923, precision=0.6923, recall=0.6923
Sample 3: f1=1.0000, precision=1.0000, recall=1.0000
Sample 4: f1=0.4444, precision=0.4000, recall=0.5000
Sample 5: f1=0.8750, precision=0.9333, recall=0.8235
Sample 6: f1=0.5714, precision=0.5000, recall=0.6667
Sample 7: f1=0.7368, precision=0.7778, recall=0.7000
Sample 8: f1=0.8235, precision=0.7778, recall=0.8750
Sample 9: f1=0.6250, precision=0.5556, recall=0.7143
avg f1=0.7441, precision=0.7172, recall=0.7818
flatten f1=0.7684, precision=0.7473, recall=0.7907
